version: "3.7"
services:
   postgres_register:
      container_name: postgres_register_ifood
      image: postgres:12.2
      environment:
         POSTGRES_USER: register
         POSTGRES_PASSWORD: register
      ports:
         - "5432:5432"
   keycloak_ifood:
      container_name: keycloak_ifood
      image: jboss/keycloak:9.0.2
      environment: 
         KEYCLOAK_USER: admin
         KEYCLOAK_PASSWORD: admin
      ports:
         - "8888:8080"
   jaeger_ifood:
      container_name: jaeger_ifood
      image: jaegertracing/all-in-one:1.3
      ports:
         - "5775:5775/udp"
         - "6831:6831/udp"
         - "6832:6832/udp"
         - "5778:5778"
         - "16686:16686"
         - "14250:14250"
         - "14268:14268"
         - "14269:14269"
         - "9411:9411"
   prometheus_ifood:
     container_name: prometheus_ifood
     image: prometheus-ifood
 #    network_mode: "host"
     ports:
        - "9090:9090"    
   grafana_ifood:
     container_name: grafana_ifood
     image: grafana/grafana:6.5.0
 #    network_mode: "host"    
     ports:
        - "3000:3000"     
   artemis_ifood:
     container_name: artemis_ifood
     image: vromero/activemq-artemis:2.11.0
#    network_mode: "host"
     ports:
         - "8161:8161"    
     environment: 
         ARTEMIS_USERNAME: admin
         ARTEMIS_PASSWORD: admin      
#   artemis_ifood:
##     image: quay.io/artemiscloud/activemq-artemis-broker:0.1.2
#     ports:
##       - "8161:8161"
#       - "61616:61616"
#       - "5672:5672"
#     environment:
#       AMQ_USER: admin
#       AMQ_PASSWORD: admin
   marketplace_ifood:
     container_name: marketplace_ifood
     image: quarkus/marketplace
   register_ifood:
     container_name: register_ifood
     image: quarkus/register         