version: "3.7"
services:
   postgres_register:
      container_name: postgres_register_ifood
      image: postgres:12.2
      environment:
         POSTGRES_USER: register
         POSTGRES_PASSWORD: register
      ports:
         - "5432:5432"
   keycloak_ifood:
      container_name: keycloak_ifood
      image: jboss/keycloak:9.0.2
      environment: 
         KEYCLOAK_USER: admin
         KEYCLOAK_PASSWORD: admin
      ports:
         - "8888:8080"       
      
       